// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvhU2jv6IsSAXL08J7y59426qMiOSFDnA',
    appId: '1:1041591229591:web:d55b5644671963ee891dd2',
    messagingSenderId: '1041591229591',
    projectId: 'cuaiet',
    authDomain: 'cuaiet.firebaseapp.com',
    storageBucket: 'cuaiet.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_0A0mbMsKyAWSsOyNRsSFTl8QEvgrbpU',
    appId: '1:1041591229591:android:94040cef5b03c8cc891dd2',
    messagingSenderId: '1041591229591',
    projectId: 'cuaiet',
    storageBucket: 'cuaiet.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBpXp1R_rr1MSkwWXikKnfRhMJf8HuADw',
    appId: '1:1041591229591:ios:a675c729abd56b67891dd2',
    messagingSenderId: '1041591229591',
    projectId: 'cuaiet',
    storageBucket: 'cuaiet.appspot.com',
    androidClientId: '1041591229591-6qm59g16u84v2p49ustvmpu4572r2f0q.apps.googleusercontent.com',
    iosClientId: '1041591229591-8u3v6qgdfpprlmr020j5772d19841p7e.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBpXp1R_rr1MSkwWXikKnfRhMJf8HuADw',
    appId: '1:1041591229591:ios:a675c729abd56b67891dd2',
    messagingSenderId: '1041591229591',
    projectId: 'cuaiet',
    storageBucket: 'cuaiet.appspot.com',
    androidClientId: '1041591229591-6qm59g16u84v2p49ustvmpu4572r2f0q.apps.googleusercontent.com',
    iosClientId: '1041591229591-8u3v6qgdfpprlmr020j5772d19841p7e.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );
}
